"""Per-session workspace for the Claude Code build chat.

Each lifeman build session corresponds to one Claude Code session running in
a per-session workspace under `~/.lifeman/build_workspaces/<sid>`. We refresh
`CLAUDE.md` in the workspace before every (re)attach so Claude Code's
project-context loader sees the current registry of installed tools and the
contract for new tools.

The actual conversation runs as a real interactive Claude Code TUI streamed
to the browser through `lifeman.build_terminal`. This module no longer wraps
`--print` / stream-json — it only owns the workspace lifecycle, the
CLAUDE.md generator, and the helpers that read finished tool artifacts back
out for registration.
"""

from __future__ import annotations

import json
import logging
import shutil
from datetime import datetime, timezone
from pathlib import Path
from textwrap import dedent

from lifeman.config import settings
from lifeman.db import get_db

log = logging.getLogger(__name__)


BUILD_SYSTEM_PROMPT = dedent(
    """\
    You are the build-chat assistant for lifeman, a personal companion AI kernel
    described in DESIGN.MD. Read CLAUDE.md in the working directory — it is
    refreshed before every turn with the current list of installed tools,
    their manifests, and the contract for new tools.

    Your job is to design and produce new tools that fit lifeman's contract.
    Discuss the design briefly with the user first, then write the artifacts to
    disk under `./out/<tool_name>/`. When you are done, tell the user the tool
    name so they can click "Register" in the lifeman UI to install it.

    Be concise. Prefer minimal dependencies. Re-use behaviors of existing tools
    where they fit instead of duplicating logic.
    """
)


CONTEXT_HEADER = dedent(
    """\
    # lifeman build-chat context

    This file is auto-regenerated by lifeman before every turn of this build
    session. Treat it as the authoritative ground truth for what tools exist
    and how to add new ones. Anything you write here will be overwritten.

    """
)


class BuildChatError(RuntimeError):
    pass


def workspace_for(session_id: str) -> Path:
    root = settings.get_build_workspace_dir()
    root.mkdir(parents=True, exist_ok=True)
    ws = root / session_id
    ws.mkdir(parents=True, exist_ok=True)
    (ws / "out").mkdir(exist_ok=True)
    return ws


# ---------------------------------------------------------------------------
# CLAUDE.md generation — gives Claude Code real ground truth about lifeman.
# ---------------------------------------------------------------------------

TOOL_CONTRACT = dedent(
    """\
    ## Tool contract

    A lifeman tool is a directory containing four files. Tools run inside a
    bubblewrap sandbox with read-only access to their own directory and a
    writable `/scratch` tmpfs. Stdin/stdout is JSON.

    ### Files
    - `run.py` — Python 3.12. Reads a JSON object from stdin, writes a JSON
      object to stdout. Exit non-zero on fatal error; otherwise return
      `{"error": "..."}` for recoverable errors so the audit log stays clean.
    - `manifest.json` — capability declaration. Schema below.
    - `schema_input.json` — JSON Schema for the args object.
    - `schema_output.json` — JSON Schema for the result object.

    ### Manifest schema
    ```json
    {
      "description": "human-readable one-liner",
      "category": "general",
      "reads": [],            // data categories the tool may read
      "writes": [],           // data categories the tool may write
      "network": [],          // host allowlist; empty = no network at all
      "compute_limits": {"timeout": 30},
      "triggers": [],         // tools/actions this tool can trigger
      "user_visible": true
    }
    ```
    Unknown fields are ignored at register time but should be omitted.

    ### Sandbox semantics
    - **Network**: the sandbox unshares the network namespace by default,
      so a tool with `network: []` has *no* network access. To request
      network access, list the hosts the tool will contact in
      `manifest.network` (or `["*"]` if you genuinely need open egress —
      flag this for the user). When the list is non-empty, the sandbox
      shares the host's network namespace and `LIFEMAN_NETWORK_HOSTS`
      contains the comma-separated allowlist. Use
      `lifeman_tool.network_allowed(host)` to self-gate requests; the
      manifest declaration is the user-visible contract. The kernel does
      not yet enforce the allowlist at the syscall level (egress proxy
      is future work).
    - No filesystem writes outside `/scratch` (path injected as
      `LIFEMAN_SCRATCH` env var inside the sandbox).
    - Default timeout is 30s; raise `compute_limits.timeout` if you need more.
    - Stdlib only by default. If you need PyPI packages, declare them in the
      design discussion so we can plan how to vendor them.

    ### Conventions
    - Names are `snake_case`. They become the tool's id in the registry.
    - Single responsibility per tool; compose by having tools call each other
      through the core `invoke` API rather than duplicating logic.
    - Every result includes a stable shape — keep field names compatible
      across versions.

    ### Surfacing results to the user
    The dict a tool returns on stdout is **not** user-visible on its own — it
    only lives in the invocation log. If the user should *see* something
    (a value, status, confirmation), call the tool-side API:

    ```python
    from lifeman_tool import notify
    notify(message="Greeting computed: hello", category="completion",
           urgency="soft", reason="show greeting to user")
    ```

    Pick `category` and `urgency` so the router sends it to a real channel:
    `completion`/`alert`/`progress`/`query` route to `web_toast`; bare
    `status`/`ambient` go to the digest and are silent in real time. If a
    user-initiated invocation finishes without emitting any output, the core
    auto-emits a fallback completion notification with the return dict — but
    a deliberate `notify()` with a human-readable message is always better.
    """
)


WORKSPACE_INSTRUCTIONS = dedent(
    """\
    ## Workspace layout

    Your current working directory is the per-session workspace. When you have
    finished building a tool, write the four files to:

    ```
    ./out/<tool_name>/run.py
    ./out/<tool_name>/manifest.json
    ./out/<tool_name>/schema_input.json
    ./out/<tool_name>/schema_output.json
    ```

    Do not register the tool yourself. Tell the user the tool name and
    instruct them to click "Register" in the lifeman UI workspace card.

    `./scratch/` is a play area for testing — anything you put there will not
    be installed.
    """
)


_DETAILED_TOOL_LIMIT = 20  # Above this, the long tail collapses to one-liners.


async def render_claude_md() -> str:
    """Build a fresh CLAUDE.md describing the live state of the registry.

    Up to `_DETAILED_TOOL_LIMIT` tools are rendered in full (manifest + both
    schemas + recent invocations). The rest collapse to a single-line
    summary so a registry of 50+ tools doesn't blow up the prompt every
    turn. The most-recently-used tools are picked for the detailed slot
    so Claude sees what's actually in active use.
    """
    db = await get_db()

    # Pick the most-recently-active tools for detailed rendering. LEFT JOIN
    # so tools with no invocations still sort in (under their name) below
    # ones with recent activity.
    rows = await db.execute_fetchall(
        """SELECT t.id, t.name, t.description, t.category,
                  MAX(i.started_at) AS last_used
             FROM tools t
             LEFT JOIN invocations i ON i.tool = t.name
            WHERE t.deprecated_at IS NULL
            GROUP BY t.id
            ORDER BY last_used DESC NULLS LAST, t.name"""
    )
    rows = [dict(r) for r in rows]

    detailed = rows[:_DETAILED_TOOL_LIMIT]
    tail = rows[_DETAILED_TOOL_LIMIT:]

    tool_blocks: list[str] = []
    for r in detailed:
        manifest_rows = await db.execute_fetchall(
            "SELECT manifest_json, schema_input_json, schema_output_json "
            "FROM tool_manifests WHERE tool_id = ? ORDER BY version DESC LIMIT 1",
            (r["id"],),
        )
        manifest: dict = {}
        schema_input: dict = {}
        schema_output: dict = {}
        if manifest_rows:
            m = dict(manifest_rows[0])
            try:
                manifest = json.loads(m["manifest_json"])
            except json.JSONDecodeError:
                manifest = {}
            try:
                schema_input = json.loads(m["schema_input_json"])
            except json.JSONDecodeError:
                schema_input = {}
            try:
                schema_output = json.loads(m["schema_output_json"])
            except json.JSONDecodeError:
                schema_output = {}

        recent = await db.execute_fetchall(
            "SELECT started_at, source, error FROM invocations WHERE tool = ? "
            "ORDER BY started_at DESC LIMIT 3",
            (r["name"],),
        )
        recent_lines = []
        for inv in recent:
            inv = dict(inv)
            status = "error" if inv.get("error") else "ok"
            recent_lines.append(f"  - {inv['started_at'][:19]} via {inv['source']} → {status}")
        recent_block = "\n".join(recent_lines) if recent_lines else "  - (no invocations yet)"

        tool_blocks.append(
            f"### `{r['name']}` — {r['description']}\n"
            f"- id: `{r['id']}`  category: `{r['category']}`\n"
            f"- manifest: `{json.dumps(manifest)}`\n"
            f"- args schema: `{json.dumps(schema_input)}`\n"
            f"- result schema: `{json.dumps(schema_output)}`\n"
            f"- recent invocations:\n{recent_block}\n"
        )

    if tool_blocks:
        installed_section = "## Installed tools\n\n" + "\n".join(tool_blocks)
    else:
        installed_section = (
            "## Installed tools\n\n"
            "_No tools installed yet. You are bootstrapping the registry — pick a tool "
            "the user asks for and build it._\n"
        )

    if tail:
        tail_lines = [
            f"- `{t['name']}` ({t['category']}) — {t['description']}"
            for t in tail
        ]
        installed_section += (
            f"\n### Other installed tools ({len(tail)} more)\n\n"
            "_Listed in compact form — ask for full manifest/schemas if you "
            "need to call or modify them._\n\n"
            + "\n".join(tail_lines) + "\n"
        )

    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    return (
        CONTEXT_HEADER
        + f"_Generated at {stamp}._\n\n"
        + installed_section
        + "\n"
        + TOOL_CONTRACT
        + "\n"
        + WORKSPACE_INSTRUCTIONS
    )


async def refresh_workspace_context(session_id: str) -> Path:
    """Regenerate `CLAUDE.md` in the workspace before a turn."""
    ws = workspace_for(session_id)
    md = await render_claude_md()
    target = ws / "CLAUDE.md"
    target.write_text(md)
    return target


def cleanup_workspace(session_id: str) -> None:
    ws = settings.get_build_workspace_dir() / session_id
    if ws.exists():
        shutil.rmtree(ws, ignore_errors=True)


def list_workspace_tools(session_id: str) -> list[dict]:
    """Inspect the workspace's `out/` dir for finished tool artifacts."""
    ws = settings.get_build_workspace_dir() / session_id / "out"
    if not ws.exists():
        return []
    tools = []
    for tool_dir in sorted(ws.iterdir()):
        if not tool_dir.is_dir():
            continue
        run_py = tool_dir / "run.py"
        manifest_path = tool_dir / "manifest.json"
        if not run_py.exists():
            continue
        manifest = {}
        if manifest_path.exists():
            try:
                manifest = json.loads(manifest_path.read_text())
            except json.JSONDecodeError:
                manifest = {"_parse_error": True}
        tools.append({
            "name": tool_dir.name,
            "path": str(tool_dir),
            "manifest": manifest,
            "code_size": run_py.stat().st_size,
        })
    return tools


def read_workspace_tool(session_id: str, name: str) -> dict | None:
    """Read a finished tool's files for registration. Returns None if missing."""
    ws = settings.get_build_workspace_dir() / session_id / "out" / name
    run_py = ws / "run.py"
    if not run_py.exists():
        return None

    code = run_py.read_text()
    manifest_path = ws / "manifest.json"
    schema_in_path = ws / "schema_input.json"
    schema_out_path = ws / "schema_output.json"

    manifest: dict = {}
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text())
        except json.JSONDecodeError:
            manifest = {}

    description = manifest.pop("description", "") if isinstance(manifest, dict) else ""
    category = manifest.pop("category", "general") if isinstance(manifest, dict) else "general"

    def _safe_load(p: Path) -> dict:
        if not p.exists():
            return {}
        try:
            return json.loads(p.read_text())
        except json.JSONDecodeError:
            return {}

    return {
        "name": name,
        "description": description,
        "category": category,
        "manifest": manifest,
        "schema_input": _safe_load(schema_in_path),
        "schema_output": _safe_load(schema_out_path),
        "code": code,
    }
